const mainProducts = [
  {
    image: "../images/products-images/White-kidney-beans.webp",
    title: "White kidney beans",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "White-kidney-beans",
    category: "Pulses and Grains",
  },
  {
    image: "../images/products-images/Whole-broad-beans.webp",
    title: "Whole broad beans",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Whole-broad-beans",
    category: "Pulses and Grains",
  },
  {
    image: "../images/products-images/Split-broad-beans.webp",
    title: "Split broad beans",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Split-broad-beans",
    category: "Pulses and Grains",
  },
  {
    image: "../images/products-images/Whole-faba-beans.webp",
    title: "Whole faba beans",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Whole-faba-beans",
    category: "Pulses and Grains",
  },
  {
    image: "../images/products-images/Peanuts.webp",
    title: "Peanuts",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Peanuts",
    category: "",
  },
  {
    image: "../images/products-images/Dry-lemon-machine-dried.webp",
    title: "Dry lemon machine dried",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Dry-lemon-machine-dried",
    category: "Pulses and Grains",
  },
  {
    image: "../images/products-images/Dry-lemon.webp",
    title: "Dry lemon",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Dry-lemon",
    category: "Pulses and Grains",
  },
  {
    image: "../images/products-images/Sesame-seeds.webp",
    title: "Sesame seeds",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Sesame-seeds",
    category: "Pulses and Grains",
  },
  {
    image: "../images/products-images/Whole-green-lentils.webp",
    title: "Whole green lentils",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Whole-green-lentils",
    category: "Pulses and Grains",
  },
  {
    image: "../images/products-images/Whole-red-lentils.webp",
    title: "Whole red lentils",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Whole-red-lentils",
    category: "Pulses and Grains",
  },
  {
    image: "../images/products-images/Split-red-lentils.webp",
    title: "Split red lentils",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Split-red-lentils",
    category: "Pulses and Grains",
  },
  {
    image: "../images/products-images/Whole-green-peans.webp",
    title: "Whole green peans",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Whole-green-peans",
    category: "Pulses and Grains",
  },
  {
    image: "../images/products-images/Split-green-peas.webp",
    title: "Split green peas",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Split-green-peas",
    category: "Pulses and Grains",
  },
  {
    image: "../images/products-images/Whole-yellow-peas.webp",
    title: "Whole yellow peas",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Whole-yellow-peas",
    category: "Pulses and Grains",
  },
  {
    image: "../images/products-images/Split-yellow-peas.webp",
    title: "Split yellow peas",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Split-yellow-peas",
    category: "Pulses and Grains",
  },
  {
    image: "../images/products-images/Chickpeas.webp",
    title: "Chickpeas",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Chickpeas",
    category: "Pulses and Grains",
  },
  {
    image: "../images/products-images/lupins.webp",
    title: "lupins",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "lupins",
    category: "Pulses and Grains",
  },
  {
    image: "../images/products-images/Black-eye-beans.webp",
    title: "Black eye beans",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Black-eye-beans",
    category: "Pulses and Grains",
  },
  {
    image: "../images/products-images/Red-kidney-beans.webp",
    title: "Red kidney beans",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Red-kidney-beans",
    category: "Pulses and Grains",
  },
  {
    image: "../images/products-images/Basmati-rice.webp",
    title: "Basmati rice",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Basmati-rice",
    category: "Pulses and Grains",
  },
  {
    image: "../images/products-images/Popcorn.webp",
    title: "Popcorn",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Popcorn",
    category: "Pulses and Grains ",
  },
  {
    image: "../images/products-images/White-millet.webp",
    title: "White millet",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "White-millet",
    category: "Pulses and Grains",
  },
  {
    image: "../images/products-images/Yellow-millet.webp",
    title: "Yellow millet",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Yellow-millet",
    category: "Pulses and Grains",
  },
  {
    image: "../images/products-images/Sorghum.webp",
    title: "Sorghum",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Sorghum",
    category: "Pulses and Grains",
  },
  {
    image: "../images/products-images/Barley-seeds.webp",
    title: "Barley seeds",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Barley-seeds",
    category: "Pulses and Grains",
  },
  {
    image: "../images/products-images/Hibiscus.webp",
    title: "Hibiscus",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Hibiscus",
    category: "Herbs and Spices",
  },
  {
    image: "../images/products-images/Dried-mellow.webp",
    title: "Dried mellow",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Dried-mellow",
    category: "Herbs and Spices",
  },
  {
    image: "../images/products-images/Black-pepper.webp",
    title: "Black pepper",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Black-pepper",
    category: "Herbs and Spices",
  },
  {
    image: "../images/products-images/Coriander.webp",
    title: "Coriander",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Coriander",
    category: "Herbs and Spices",
  },
  {
    image: "../images/products-images/Carawy-seeds.webp",
    title: "Carawy seeds",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Carawy-seeds",
    category: "Herbs and Spices",
  },
  {
    image: "../images/products-images/Fennel-seeds.webp",
    title: "Fennel seeds",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Fennel-seeds",
    category: "Herbs and Spices",
  },
  {
    image: "../images/products-images/Anise-seeds.webp",
    title: "Anise seeds",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Anise-seeds",
    category: "Herbs and Spices",
  },
  {
    image: "../images/products-images/Cumin-seeds.webp",
    title: "Cumin seeds",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Cumin-seeds",
    category: "Herbs and Spices",
  },
  {
    image: "../images/products-images/Black-seeds.webp",
    title: "Black seeds (nigella seeds)",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Black-seeds",
    category: "Herbs and Spices",
  },
  {
    image: "../images/products-images/Dry-ginger.webp",
    title: "Dry ginger",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Dry-ginger",
    category: "Herbs and Spices",
  },
  {
    image: "../images/products-images/Bay-laurel.webp",
    title: "Bay laurel",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Bay-laurel",
    category: "Herbs and Spices",
  },
  {
    image: "../images/products-images/Nutmeg.webp",
    title: "Nutmeg",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Nutmeg",
    category: "Herbs and Spices",
  },
  {
    image: "../images/products-images/Dried-garlic.webp",
    title: "Dried garlic",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Dried-garlic",
    category: "Herbs and Spices",
  },
  {
    image: "../images/products-images/Asaliya-seeds.webp",
    title: "Asaliya seeds",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Asaliya-seeds",
    category: "Herbs and Spices",
  },
  {
    image: "../images/products-images/Frankincense.webp",
    title: "Frankincense",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Frankincense",
    category: "Herbs and Spices",
  },
  {
    image: "../images/products-images/Galngal.webp",
    title: "Galngal",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Galngal",
    category: "Herbs and Spices",
  },
  {
    image: "../images/products-images/Cigar-cinnamon.webp",
    title: "Cigar cinnamon",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Cigar-cinnamon",
    category: "Herbs and Spices",
  },
  {
    image: "../images/products-images/Mustard-seeds.webp",
    title: "Mustard seeds",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Mustard-seeds",
    category: "Herbs and Spices",
  },
  {
    image: "../images/products-images/Oats.webp",
    title: "Oats",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Oats",
    category: "Herbs and Spices",
  },
  {
    image: "../images/products-images/Cardamom.webp",
    title: "Cardamom",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Cardamom",
    category: "Herbs and Spices",
  },
  {
    image: "../images/products-images/Flax-seeds.webp",
    title: "Flax seeds",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Flax-seeds",
    category: "Herbs and Spices",
  },
  {
    image: "../images/products-images/Fenugreek.webp",
    title: "Fenugreek",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Fenugreek",
    category: "Herbs and Spices",
  },
  {
    image: "../images/products-images/Sunflower-seeds.webp",
    title: "Sunflower seeds",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Sunflower-seeds",
    category: "Herbs and Spices",
  },
  {
    image: "../images/products-images/Pumpkin-Seeds.webp",
    title: "Pumpkin Seeds",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Pumpkin-Seeds",
    category: "Herbs and Spices",
  },
  {
    image: "../images/products-images/Blanched-peanuts.webp",
    title: "Blanched peanuts",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Blanched-peanuts",
    category: "Herbs and Spices",
  },
  {
    image: "../images/products-images/Split-blanched-peanuts.webp",
    title: "Split blanched peanuts",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Split-blanched-peanuts",
    category: "Herbs and Spices",
  },
  {
    image: "../images/products-images/Hazelnut-kernels.webp",
    title: "Hazelnut kernels",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Hazelnut-kernels",
    category: "Nuts",
  },
  {
    image: "../images/products-images/Balnched-hazelnut.webp",
    title: "Balnched hazelnut",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Balnched-hazelnut",
    category: "Nuts",
  },
  {
    image: "../images/products-images/Almond-kernels.webp",
    title: "Almond kernels",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Almond-kernels",
    category: "Nuts",
  },
  {
    image: "../images/products-images/Pistachio-kernels.webp",
    title: "Pistachio kernels",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Pistachio-kernels",
    category: "Nuts",
  },
  {
    image: "../images/products-images/Pistachio-green-skin.webp",
    title: "Pistachio green skin",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Pistachio-green-skin",
    category: "Nuts",
  },
  {
    image: "../images/products-images/Cashew-kernels.webp",
    title: "Cashew kernels",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Cashew-kernels",
    category: "Nuts",
  },
  {
    image: "../images/products-images/Raw-walnut.webp",
    title: "Raw walnut",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Raw-walnut",
    category: "Nuts",
  },
  {
    image: "../images/products-images/Walnut-kernels.webp",
    title: "Walnut kernels",
    rate: "starIcon",
    size: "Bag/25k",
    altImg: "Walnut-kernels",
    category: "Nuts",
  },
];

const productSection = document.querySelector(".products");
const productHolder = document.getElementById("product-holder");

const viewMainProducts = () => {
  for (let i = 0; i < mainProducts.length; i++) {
    const productCard = document.createElement("div");
    productCard.classList.add("product-card");
    productHolder.appendChild(productCard);
    const prodImageHolder = document.createElement("div");
    prodImageHolder.classList.add("image-holder");
    const prodImage = document.createElement("img");
    prodImage.classList.add("product-img");
    const prodTitle = document.createElement("p");
    prodTitle.classList.add("product-title");
    const prodSize = document.createElement("p");
    prodSize.classList.add("product-size");
    productCard.appendChild(prodImageHolder);
    prodImageHolder.appendChild(prodImage);
    productCard.appendChild(prodTitle);
    prodImage.src = mainProducts[i].image;
    prodImage.alt = mainProducts[i].altImg;
    prodTitle.innerHTML = mainProducts[i].title;
    for (let j = 0; j < 5; j++) {
      const prodRate = document.createElement("i");
      prodRate.classList.add("fa-solid");
      prodRate.classList.add("fa-star");
      productCard.appendChild(prodRate);
      productCard.appendChild(prodSize);
    }
    prodSize.innerHTML = mainProducts[i].size;
  }
};
viewMainProducts();
